### ISSUE TITLE
Couldn't parse data file

### ISSUE THREAD

**Issue by bookerthegeek** [Gaelmare/WaterFlasks#27]
### Heyo!

MC: 1.20.1
WF: 3.0.4

```
[15:16:09] [Render thread/INFO] [patchouli/]: BookContentResourceListenerLoader preloaded 756 jsons
[15:16:49] [Worker-Main-19/ERROR] [minecraft/SimpleJsonResourceReloadListener]: Couldn't parse data file waterflasks:unfinished_iron_flask from waterflasks:tfc/item_heats/unfinished_iron_flask.json
com.google.gson.JsonParseException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 2 path $
	at net.minecraft.util.GsonHelper.m_13780_(GsonHelper.java:526) ~[client-1.20.1-20230612.114412-srg.jar%23252!/:?] {re:classloading,re:mixin}
	at net.minecraft.util.GsonHelper.m_263475_(GsonHelper.java:531) ~[client-1.20.1-20230612.114412-srg.jar%23252!/:?] {re:classloading,re:mixin}
	at net.minecraft.util.GsonHelper.m_13776_(GsonHelper.java:581) ~[client-1.20.1-20230612.114412-srg.jar%23252!/:?] {re:classloading,re:mixin}
	at net.minecraft.server.packs.resources.SimpleJsonResourceReloadListener.m_278771_(SimpleJsonResourceReloadListener.java:41) ~[client-1.20.1-20230612.114412-srg.jar%23252!/:?] {re:mixin,re:computing_frames,re:classloading}
	at net.minecraft.server.packs.resources.SimpleJsonResourceReloadListener.m_5944_(SimpleJsonResourceReloadListener.java:29) ~[client-1.20.1-20230612.114412-srg.jar%23252!/:?] {re:mixin,re:computing_frames,re:classloading}
	at net.minecraft.server.packs.resources.SimpleJsonResourceReloadListener.m_5944_(SimpleJsonResourceReloadListener.java:17) ~[client-1.20.1-20230612.114412-srg.jar%23252!/:?] {re:mixin,re:computing_frames,re:classloading}
	at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10786_(SimplePreparableReloadListener.java:11) ~[client-1.20.1-20230612.114412-srg.jar%23252!/:?] {re:mixin,re:classloading,pl:mixin:APP:moonlight.mixins.json:ConditionHackMixin,pl:mixin:A}
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?] {}
```

just need to remove the first line of the json file is all to remove this error from showing up in the log.

**Comment by Coach-mdl** [comment]
Yeah that was my fault. After a long day of doing KJS stuff, I accidentally did the KJS method instead of the json method for comments.

**Comment by Gaelmare** [comment]
Fixed in https://github.com/Gaelmare/WaterFlasks/commit/f19975fa9ee0c2d457181fc66d6539b05d5d623b
